services:
  php:
    build:
      context: ./docker
    restart: always
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - '.:/var/www/html'
      - './docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    env_file:
      - .env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - '.:/var/www/html'
      - './docker/conf/nginx:/etc/nginx/conf.d'
    depends_on:
      - php
      - db

  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 54321:5432
    volumes:
      - './docker/postgres/data:/var/lib/postgresql/data'

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
        - ./rabbitmq:/var/lib/rabbitmq
    ports:
        - 15672:15672
        - 5672:5672
